# Dockerfile.spark

# 1. Start with Python 3.10
FROM python:3.10-slim-bookworm

USER root

# 2. Install Java (Required for Spark) and procps
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless procps curl && \
    rm -rf /var/lib/apt/lists/*

# 3. Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

# 4. Install Spark 3.5.0
ENV SPARK_VERSION=3.5.0
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark

RUN curl -L https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz -o spark.tgz && \
    tar -xf spark.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark && \
    rm spark.tgz

# 5. Add Spark to PATH
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

# 6. Install Python dependencies
RUN pip install --no-cache-dir pyspark==${SPARK_VERSION} pandas numpy boto3

WORKDIR /opt/spark/jars

RUN curl -O https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
RUN curl -O https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# Return to original Spark dir
WORKDIR /opt/spark

WORKDIR /opt/spark