version: "3.9"

# ==========================================
# Reusable Airflow Configuration
# ==========================================
x-airflow-common: &airflow-common
    build:
        context: .
        dockerfile: Dockerfile
    environment: &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        AIRFLOW__CORE__FERNET_KEY: ""
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
        AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
        AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
        AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
        AWS_DEFAULT_REGION: us-east-1
    volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./plugins:/opt/airflow/plugins
        - ./src:/opt/workspace
    networks:
        - de-network

services:
    minio:
        image: quay.io/minio/minio
        container_name: minio
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            - ./data/minio:/data
            - ./data/raw:/raw_mount
        ports:
            - "9000:9000"
            - "9001:9001"
        networks:
            - de-network

    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - gene_drug_postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always
        networks:
            - de-network

    spark-master:
        build:
            context: .
            dockerfile: dockerfile.spark
        container_name: spark-master
        environment:
            - SPARK_MODE=master
            - SPARK_MASTER_HOST=spark-master
        command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host 0.0.0.0 --port 7077
        ports:
            - "7077:7077"
            - "8080:8080"
        networks:
            - de-network

    spark-worker:
        build:
            context: .
            dockerfile: dockerfile.spark
        container_name: spark-worker
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER=spark://spark-master:7077
        depends_on:
            - spark-master
        command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        ports:
            - "8090:8090"
        networks:
            - de-network

    # ##############################
    # Airflow Init (Runs once, then dies)
    # ##############################
    airflow-init:
        <<: *airflow-common
        container_name: airflow-init
        command: >
            bash -c "
            airflow db migrate &&
            airflow connections create-default-connections &&
            airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com || true
            "
        depends_on:
            postgres:
                condition: service_healthy

    # ##############################
    # Airflow Webserver
    # ##############################
    airflow:
        <<: *airflow-common
        container_name: airflow
        ports:
            - "8081:8080"
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        command: bash -c "exec airflow webserver"
        depends_on:
            airflow-init:
                condition: service_completed_successfully

    # ##############################
    # Airflow Scheduler
    # ##############################
    airflow-scheduler:
        <<: *airflow-common
        container_name: airflow-scheduler
        command: bash -c "exec airflow scheduler"
        depends_on:
            airflow-init:
                condition: service_completed_successfully

    jupyter:
        # image: jupyter/pyspark-notebook:spark-3.3.2
        build:
            context: .
            dockerfile: dockerfile.jupyter
        container_name: jupyter
        user: root
        environment:
            - JUPYTER_TOKEN=admin
            - SPARK_MASTER=spark://spark-master:7077
            # - SPARK_HOME=/usr/local/spark
            - SPARK_DRIVER_BIND_ADDRESS=0.0.0.0
            - PYSPARK_SUBMIT_ARGS=--conf spark.driver.bindAddress=0.0.0.0 --master spark://spark-master:7077 pyspark-shell
            - SPARK_DRIVER_HOST=jupyter
        ports:
            - "8888:8888"
        volumes:
            - ./src:/home/jovyan/work
            - ./data/raw:/raw_mount
        depends_on:
            - spark-master
        networks:
            - de-network

networks:
    de-network:
        driver: bridge

volumes:
    gene_drug_postgres_data:
